-- MASTER SQL: migrate to single unified registration model, reset forms, seed new form, and clear old data
BEGIN;

-- 1) success_enroll: add new columns (idempotent)
ALTER TABLE public.success_enroll ADD COLUMN IF NOT EXISTS registration_mode text CHECK (registration_mode in ('solo','group'));
ALTER TABLE public.success_enroll ADD COLUMN IF NOT EXISTS participants_count integer;
ALTER TABLE public.success_enroll ADD COLUMN IF NOT EXISTS participants jsonb DEFAULT '[]'::jsonb;
-- Keep form_data jsonb as canonical payload (already exists per schema)
ALTER TABLE public.success_enroll ALTER COLUMN currency SET DEFAULT 'NGN';

-- Optional: drop legacy category if you want to fully remove it
-- ALTER TABLE public.success_enroll DROP COLUMN IF EXISTS category;

-- 2) Clear existing success_enroll data
TRUNCATE TABLE public.success_enroll RESTART IDENTITY CASCADE;

-- 3) Forms: remove old individual/family program_forms and seed unified form to every program
-- Ensure form_type enum contains a suitable single value; reuse 'individual' as the unified type
DELETE FROM public.program_forms WHERE form_type IN ('family_head','family_member');
DELETE FROM public.program_forms WHERE form_type = 'individual';

-- Seed a new unified schema to each program (Google Forms style schema)
-- The UI uses a custom rendered form now, but keeping a schema is helpful for admin export and future changes
INSERT INTO public.program_forms (program_id, form_type, schema)
SELECT p.id, 'individual',
       jsonb_build_object(
         'title', 'Unified Registration Form',
         'description', 'Register yourself or a group (family & friends).',
         'fields', jsonb_build_array(
            jsonb_build_object('id','payer_full_name','label','Your full name','type','text','required',true),
            jsonb_build_object('id','payer_email','label','Your email','type','email','required',true),
            jsonb_build_object('id','payer_phone','label','Phone','type','text','required',false),
            jsonb_build_object('id','payer_country','label','Country','type','text','required',false),
            jsonb_build_object('id','registration_mode','label','Registering for','type','select','required',true,'options', jsonb_build_array('solo','group')),
            jsonb_build_object('id','participant_count','label','Number of participants','type','number','required',true),
            jsonb_build_object('id','participants','label','Participants','type','textarea','required',false,'description','JSON array of {name,email} (auto-generated by UI)'),
            jsonb_build_object('id','goals','label','What are your goals?','type','textarea','required',false),
            jsonb_build_object('id','notes','label','Notes for admin','type','textarea','required',false)
         )
       )
FROM public.programs p;

COMMIT;
